import { atom } from 'jotai'

import user from '@/assets/images/user.png'
import { UsersInterface } from '@/types'

const mockDataUsers: UsersInterface[] = [
  {
    _id: '1',
    email: 'jessica.jane@example.com',
    password: 'hashedpassword123',
    account_role: 1,
    specialization: 'Web Development',
    position: 'Senior Web Developer',
    username: 'Jessica Jane',
    description:
      "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web Development.",
    phone_number: '123-456-7890',
    skills: ['ReactJS', 'JavaScript', 'Node.js'],
    avatar: user,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2023-01-01'),
    date: '23/02/2002',
  },
  {
    _id: '1',
    email: 'jessica.jane@example.com',
    password: 'hashedpassword123',
    account_role: 1,
    specialization: 'Web Development',
    position: 'Senior Web Developer',
    username: 'Jessica Jane',
    description:
      "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web Development.",
    phone_number: '123-456-7890',
    skills: ['ReactJS', 'JavaScript', 'Node.js'],
    avatar: user,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2023-01-01'),
    date: '23/02/2002',
  },
  {
    _id: '1',
    email: 'jessica.jane@example.com',
    password: 'hashedpassword123',
    account_role: 1,
    specialization: 'Web Development',
    position: 'Senior Web Developer',
    username: 'Jessica Jane',
    description:
      "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web Development.",
    phone_number: '123-456-7890',
    skills: ['ReactJS', 'JavaScript', 'Node.js'],
    avatar: user,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2023-01-01'),
    date: '23/02/2002',
  },
  {
    _id: '1',
    email: 'jessica.jane@example.com',
    password: 'hashedpassword123',
    account_role: 1,
    specialization: 'Web Development',
    position: 'Senior Web Developer',
    username: 'Jessica Jane',
    description:
      "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web Development.",
    phone_number: '123-456-7890',
    skills: ['ReactJS', 'JavaScript', 'Node.js'],
    avatar: user,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2023-01-01'),
    date: '23/02/2002',
  },
  {
    _id: '1',
    email: 'jessica.jane@example.com',
    password: 'hashedpassword123',
    account_role: 1,
    specialization: 'Web Development',
    position: 'Senior Web Developer',
    username: 'Jessica Jane',
    description:
      "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web Development.",
    phone_number: '123-456-7890',
    skills: ['ReactJS', 'JavaScript', 'Node.js'],
    avatar: user,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2023-01-01'),
    date: '23/02/2002',
  },
  {
    _id: '1',
    email: 'jessica.jane@example.com',
    password: 'hashedpassword123',
    account_role: 1,
    specialization: 'Web Development',
    position: 'Senior Web Developer',
    username: 'Jessica Jane',
    description:
      "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web Development.",
    phone_number: '123-456-7890',
    skills: ['ReactJS', 'JavaScript', 'Node.js'],
    avatar: user,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2023-01-01'),
    date: '23/02/2002',
  },
  {
    _id: '1',
    email: 'jessica.jane@example.com',
    password: 'hashedpassword123',
    account_role: 1,
    specialization: 'Web Development',
    position: 'Senior Web Developer',
    username: 'Jessica Jane',
    description:
      "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web Development.",
    phone_number: '123-456-7890',
    skills: ['ReactJS', 'JavaScript', 'Node.js'],
    avatar: user,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2023-01-01'),
    date: '23/02/2002',
  },
  {
    _id: '1',
    email: 'jessica.jane@example.com',
    password: 'hashedpassword123',
    account_role: 1,
    specialization: 'Web Development',
    position: 'Senior Web Developer',
    username: 'Jessica Jane',
    description:
      "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web Development.",
    phone_number: '123-456-7890',
    skills: ['ReactJS', 'JavaScript', 'Node.js'],
    avatar: user,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2023-01-01'),
    date: '23/02/2002',
  },
  {
    _id: '1',
    email: 'jessica.jane@example.com',
    password: 'hashedpassword123',
    account_role: 1,
    specialization: 'Web Development',
    position: 'Senior Web Developer',
    username: 'Jessica Jane',
    description:
      "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web Development.",
    phone_number: '123-456-7890',
    skills: ['ReactJS', 'JavaScript', 'Node.js'],
    avatar: user,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2023-01-01'),
    date: '23/02/2002',
  },
  {
    _id: '1',
    email: 'jessica.jane@example.com',
    password: 'hashedpassword123',
    account_role: 1,
    specialization: 'Web Development',
    position: 'Senior Web Developer',
    username: 'Jessica Jane',
    description:
      "Hi, I'm Jessica Jane. I am a doctoral student at Harvard University majoring in Web Development.",
    phone_number: '123-456-7890',
    skills: ['ReactJS', 'JavaScript', 'Node.js'],
    avatar: user,
    createdAt: new Date('2022-01-01'),
    updatedAt: new Date('2023-01-01'),
    date: '23/02/2002',
  },
]

export const dataUsers = atom<UsersInterface[]>(mockDataUsers)
